// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxyqjiotmepqqpwmqjvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4eXFqaW90bWVwcXFwd21xanZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTQzMjYsImV4cCI6MjA2ODgzMDMyNn0.-BveYbYAFGv-p6waio7MTzKcnfoQDZ7mf1WJyloOkfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});